### ISSUE TITLE
Něco málo se tu našlo

### ISSUE THREAD

**Issue by mohlerit** [KristynRiho/DU_01-zivotopis#1]
Ahoj budoucí super kodérko :-)
Dneska to zkouknu za Verču. 

Mock hezká stránka i obsahově. Pobavilo mě to :-). Mám tady ale pár věcí. 

Začnu s CSS. Upřímně zde jis mě překvapila. Přiznám se, že zde vidím části které vídám, rozumím jim, ale když jsem aktivně dělal CSS tak ještě neexistovali. Tvůj level CSS je dle mého na vyskové úrovni.

Občas jsem si věiml, že v CSS používáš zápis barvy anglickým názvem. Není to špatně. Běžně se to v CSS ale nepoužívá v praxi. Doporučuji si vybrat styl hexadcimálního zápisu (#ffffff) nebo RGB zápisu ( rgb(255, 255, 255) ) a ten používat v celém CSS. 

Co mě v CSS ještě zamrzelo je použití `!important`. Domnívám se, že by stačilo změnit pořadí a `.about--bio` přesunout až pod `about`. `!important` se snaž nepoužívát. Používá se ve velmi vyjímečných případech.

Dostáváme se k HTML. Tam mám několik vážnějších připomínek, ale neboj se číst dále.

index.html řádek 81 máč v tagu `option` tag `span`. Tím pádem se nejdná o vladní HTML, protože v `option` by neměl být zanořený další tag.

Dále niže ve formuláři máš špatně použité `for` u `label` pro `q2` a `q3`. Směřuje to na `id` formuláře, ale má to směřovat na `id` tagu `input` nebo `select` nebo jiného formulářového prvku. Tag `form` není použitý v hodně, ale to se naučíš ještě v dalších lekcích :-)

U aboutMe.html bych doporučil přejmenování na `about-me.html`. Může to dělat někde neplaechu. Doporučuji pobecně používat malé písmena a nepouřívat diakritiku. Předejdeš tak možným problémům v budoucnosti, které mohou nastat na jiných začízeních. 

Dále v aboutMe.html na řádku 37 a 39 máš překlep. Máš tam atribut `target` s hodnotou `__blank` správně je ale `_blank` s jendám podtržitkem. 

No a poslední připomínka je, že máš v na řádku 82 v párovém tagu `table` nějaký `div` ten do tabilky nepatří. Je to pak neavalidní kód i když to vypadá že to funguje. Může to dělat jinde problémy.

Pro kontorlu HTML doporučuji používat https://validator.w3.org/ 

## Podmínky pro ohodnocení 

- [x] upravit `__blank` na `_blank`
- [x] zbavit se divu v tabulce
- [x] zbavit se tagu `span` v tagu `option`

## Odpovědi na otázky 

Jak zvětšit ikonky pro facebook a linkedin? Celkově jsem měla práci s nimi hýbat :-( Jsou nahrané z https://fontawesome.com/, je to dobrý zdroj pro ikonky, nebo doporučíš jiný zdroj na ikonky?

Odpověď: Pomocí `font-size` berou se jako písmo. Osobně znám a používám https://icons.getbootstrap.com/ ale internet je plný různách ikon. Lze si dělat i vlastní.

Jak udělat, aby se tlačítko "zpět na začátek stránky" (nachází se na konci stránky dole vpravo a odkazuje zpět na začátek stránky) zobrazilo při čtení stránky hned za "header" a pak si udržovalo pozici, to už bude třeba řešit přes Javascript nebo ne? Zde je ukázka, co přesně mám na mysli https://lavendy.cz/ - když čtenář roluje dolů, hned za úvodní fotografii se zobrazí tlačítko "zpět na začátek stránky"

Odpověď: Přilepení provedeš pomocí `position: absolute` a nastavení valstností `right` a `bottom`. A ano scroolování níže a zobrazení se dělí pomocí JavaScriptu

v sekci "třoška serioznosti (aboutMe.html)" - jednotlivé podsekce ("kdo jsem", "co jsem dokazala", "vzdelavam se", "rozumim nekomu") mám zabalit taky do tagu "section", nebo ted jsem objevila "article" a nebo to nemusím zabalovat do ničeho, když je to jen pár řádek a ani to nijak neformátuji?

Odpověď: Toto je relaivně dlouhe tema, které doporučím vznést třeba na konzultaci jak co kdy použít. V tomto případě si myslím, že `section` je v pořádku. 

Jinak příště otázky nedávej do read me, ale do issues :-)

**Comment by KristynRiho** [comment]
Ahoj Martine, moc ti děkuji za zpětnou vazbu! Požadované opravy jsem provedla. 
Měla bych ještě jeden dotaz, když tag  option nemůže mít v sobě vnořený další tag, jak bych tam udělala tučné slovo? Díky moc.

**Comment by mohlerit** [comment]
Ahoj,
dobrá otázka. Donutila jsi mě k zamyšlení. Pak jsme teda googlil a je to jak jsem si to myslel. Není to možné udělat pomocí HTML. Je potřeba pomocí HTML, CSS a JavaScript udělat dropdown select, který může vypadat jak select, ale ve skutešnosti to je třeba sada seskáladných divů a seznamu up. S tím, že na stránce máš neviditelný select, kde se vybírá hodnota javascriptem. Nějaké hotové řešení jistě bude na internetu.
